---
root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:mocha/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - 'off'
    - always
    # - error
    # - 2
    # - ignoredNodes: ['ConditionalExpression']
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
    - beforeStatementContinuationChars: always
overrides:
  - files: ['*.json']
    rules:
      quotes: ['error', 'double']
